-- Baseline migratie: legt het schema vast zoals het door Hibernate (ddl-auto)
-- werd gegenereerd op het moment dat Flyway werd geïntroduceerd.
--
-- Gegenereerd door de app lokaal te starten tegen een lege database met
-- spring.jpa.hibernate.ddl-auto=create, en het resultaat te dumpen met
-- pg_dump --schema-only. Vanaf hier neemt Flyway het schemabeheer over
-- (ddl-auto gaat naar 'validate') en komen alle volgende wijzigingen als
-- nieuwe, genummerde migraties (V2__..., V3__..., ...).
--
-- Tegen een reeds bestaande (prod-)database: gebruik `flyway baseline`
-- zodat deze migratie als "al toegepast" wordt gemarkeerd zonder opnieuw
-- te worden uitgevoerd. Tegen een verse database (CI, lokale ontwikkeling,
-- disaster recovery) voert Flyway dit bestand gewoon echt uit.

--
-- Name: announcements; Type: TABLE; Schema: public
--

CREATE TABLE public.announcements (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    type character varying(20) NOT NULL,
    author character varying(80),
    title character varying(120) NOT NULL,
    body character varying(2000) NOT NULL,
    CONSTRAINT announcements_type_check CHECK (((type)::text = ANY ((ARRAY['mededeling'::character varying, 'onderhoud'::character varying, 'evenement'::character varying])::text[])))
);

ALTER TABLE public.announcements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: cleaning_tasks; Type: TABLE; Schema: public
--

CREATE TABLE public.cleaning_tasks (
    completed boolean NOT NULL,
    deadline date,
    week_number integer NOT NULL,
    assigned_to_id bigint,
    id bigint NOT NULL,
    role_access character varying(20) NOT NULL,
    name character varying(120) NOT NULL,
    comment character varying(1000),
    description character varying(1000),
    incident_report character varying(1000),
    CONSTRAINT cleaning_tasks_week_number_check CHECK (((week_number <= 53) AND (week_number >= 1)))
);

ALTER TABLE public.cleaning_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cleaning_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: documents; Type: TABLE; Schema: public
--

CREATE TABLE public.documents (
    id bigint NOT NULL,
    uploaded_by_id bigint NOT NULL,
    role_access character varying(20) NOT NULL,
    title character varying(120) NOT NULL,
    storage_path character varying(512) NOT NULL,
    description character varying(1000)
);

ALTER TABLE public.documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: email_templates; Type: TABLE; Schema: public
--

CREATE TABLE public.email_templates (
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    type character varying(30) NOT NULL,
    subject character varying(200) NOT NULL,
    body text NOT NULL,
    CONSTRAINT email_templates_type_check CHECK (((type)::text = ANY ((ARRAY['PAYMENT_NEW'::character varying, 'PAYMENT_REMINDER_1'::character varying, 'PAYMENT_REMINDER_2'::character varying, 'OVERDUE'::character varying, 'MISSED_CLEANING'::character varying])::text[])))
);

ALTER TABLE public.email_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: huisregels; Type: TABLE; Schema: public
--

CREATE TABLE public.huisregels (
    order_index integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone,
    title character varying(200) NOT NULL,
    content text
);

ALTER TABLE public.huisregels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.huisregels_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: invoices; Type: TABLE; Schema: public
--

CREATE TABLE public.invoices (
    amount numeric(10,2) NOT NULL,
    due_date date NOT NULL,
    invoice_month integer NOT NULL,
    invoice_year integer NOT NULL,
    issue_date date NOT NULL,
    reminder_count integer NOT NULL,
    id bigint NOT NULL,
    last_reminder_sent_at timestamp(6) without time zone,
    paid_at timestamp(6) without time zone,
    student_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    mollie_payment_id character varying(50),
    title character varying(120) NOT NULL,
    checkout_url character varying(512),
    description character varying(1000),
    CONSTRAINT invoices_invoice_month_check CHECK (((invoice_month <= 12) AND (invoice_month >= 1))),
    CONSTRAINT invoices_invoice_year_check CHECK (((invoice_year >= 2000) AND (invoice_year <= 2100))),
    CONSTRAINT invoices_reminder_count_check CHECK ((reminder_count >= 0)),
    CONSTRAINT invoices_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'PAID'::character varying, 'OVERDUE'::character varying, 'CANCELLED'::character varying])::text[])))
);

ALTER TABLE public.invoices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: password_reset_tokens; Type: TABLE; Schema: public
--

CREATE TABLE public.password_reset_tokens (
    expires_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    used_at timestamp(6) with time zone,
    user_id bigint NOT NULL,
    token character varying(64) NOT NULL
);

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: payments; Type: TABLE; Schema: public
--

CREATE TABLE public.payments (
    amount numeric(10,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    paid_at timestamp(6) without time zone,
    student_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    description character varying(500),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'PENDING'::character varying, 'PAID'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])))
);

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: rooms; Type: TABLE; Schema: public
--

CREATE TABLE public.rooms (
    id bigint NOT NULL,
    occupant_id bigint,
    name character varying(50) NOT NULL
);

ALTER TABLE public.rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: shifts; Type: TABLE; Schema: public
--

CREATE TABLE public.shifts (
    shift_date date NOT NULL,
    check_in_at timestamp(6) with time zone,
    check_out_at timestamp(6) with time zone,
    cleaner_id bigint NOT NULL,
    id bigint NOT NULL,
    notes character varying(500)
);

ALTER TABLE public.shifts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shifts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: supply_reports; Type: TABLE; Schema: public
--

CREATE TABLE public.supply_reports (
    id bigint NOT NULL,
    reported_at timestamp(6) with time zone NOT NULL,
    reported_by_id bigint NOT NULL,
    updated_at timestamp(6) with time zone,
    status character varying(20) NOT NULL,
    urgency character varying(20) NOT NULL,
    item_name character varying(200) NOT NULL,
    notes character varying(500),
    CONSTRAINT supply_reports_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ORDERED'::character varying, 'RECEIVED'::character varying])::text[]))),
    CONSTRAINT supply_reports_urgency_check CHECK (((urgency)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying])::text[])))
);

ALTER TABLE public.supply_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supply_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: task_photos; Type: TABLE; Schema: public
--

CREATE TABLE public.task_photos (
    id bigint NOT NULL,
    task_id bigint NOT NULL,
    uploaded_at timestamp(6) with time zone NOT NULL,
    uploaded_by_id bigint NOT NULL,
    photo_path character varying(500) NOT NULL
);

ALTER TABLE public.task_photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: users; Type: TABLE; Schema: public
--

CREATE TABLE public.users (
    rent_amount numeric(10,2),
    status_toggle boolean NOT NULL,
    id bigint NOT NULL,
    meal_preference character varying(10),
    role character varying(20) NOT NULL,
    availability_status character varying(30),
    emergency_phone_number character varying(30),
    phone_number character varying(30),
    social_preference character varying(30),
    username character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    favorite_meal character varying(100),
    full_name character varying(100),
    study_or_work character varying(100),
    contract_file character varying(255),
    parents_address character varying(255),
    password character varying(255) NOT NULL,
    profile_image_path character varying(255),
    CONSTRAINT users_availability_status_check CHECK (((availability_status)::text = ANY ((ARRAY['TENTAMENPERIODE'::character varying, 'DRUK'::character varying, 'OPEN_VOOR_CHILLEN'::character varying])::text[]))),
    CONSTRAINT users_meal_preference_check CHECK (((meal_preference)::text = ANY ((ARRAY['JA'::character varying, 'SOMS'::character varying, 'NEE'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'STUDENT'::character varying, 'CLEANER'::character varying])::text[]))),
    CONSTRAINT users_social_preference_check CHECK (((social_preference)::text = ANY ((ARRAY['OPEN_FOR_CONTACT'::character varying, 'LEUK'::character varying, 'AF_EN_TOE'::character varying, 'LIEVER_OP_MEZELF'::character varying])::text[])))
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Primary keys / unique constraints
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT announcements_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cleaning_tasks
    ADD CONSTRAINT cleaning_tasks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_storage_path_key UNIQUE (storage_path);

ALTER TABLE ONLY public.email_templates
    ADD CONSTRAINT email_templates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.email_templates
    ADD CONSTRAINT email_templates_type_key UNIQUE (type);

ALTER TABLE ONLY public.huisregels
    ADD CONSTRAINT huisregels_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_token_key UNIQUE (token);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_name_key UNIQUE (name);

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_occupant_id_key UNIQUE (occupant_id);

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.shifts
    ADD CONSTRAINT shifts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.supply_reports
    ADD CONSTRAINT supply_reports_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.task_photos
    ADD CONSTRAINT task_photos_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_user_username UNIQUE (username);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

--
-- Indexes
--

CREATE INDEX idx_cleaning_task_assigned ON public.cleaning_tasks USING btree (assigned_to_id);

CREATE INDEX idx_cleaning_task_completed ON public.cleaning_tasks USING btree (completed);

CREATE INDEX idx_cleaning_task_week_id ON public.cleaning_tasks USING btree (week_number, id);

CREATE INDEX idx_document_role_access ON public.documents USING btree (role_access);

CREATE INDEX idx_document_uploaded_by ON public.documents USING btree (uploaded_by_id);

CREATE INDEX idx_invoice_due_date ON public.invoices USING btree (due_date);

CREATE INDEX idx_invoice_status ON public.invoices USING btree (status);

CREATE INDEX idx_invoice_student ON public.invoices USING btree (student_id);

CREATE INDEX idx_invoice_year_month ON public.invoices USING btree (invoice_year, invoice_month);

CREATE INDEX idx_payment_paid_at ON public.payments USING btree (paid_at);

CREATE INDEX idx_payment_status ON public.payments USING btree (status);

CREATE INDEX idx_payment_student ON public.payments USING btree (student_id);

CREATE INDEX idx_room_name ON public.rooms USING btree (name);

CREATE INDEX idx_room_occupant ON public.rooms USING btree (occupant_id);

CREATE INDEX idx_shifts_cleaner_date ON public.shifts USING btree (cleaner_id, shift_date);

CREATE INDEX idx_task_photos_task ON public.task_photos USING btree (task_id);

--
-- Foreign keys
--

ALTER TABLE ONLY public.task_photos
    ADD CONSTRAINT fk4ljcj6hkgd398cgqo3bvv8bbx FOREIGN KEY (task_id) REFERENCES public.cleaning_tasks(id);

ALTER TABLE ONLY public.cleaning_tasks
    ADD CONSTRAINT fk57jx9edf8csrxviimmuhj6xx2 FOREIGN KEY (assigned_to_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.supply_reports
    ADD CONSTRAINT fk5xhcyu1b39p60rsnhw75vy71g FOREIGN KEY (reported_by_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.task_photos
    ADD CONSTRAINT fk7hrqh47a5u0r3jvri58nb8gyc FOREIGN KEY (uploaded_by_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fka8xyugvg1b1gjr07r5057pn5 FOREIGN KEY (uploaded_by_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT fkakkfiaesng8bjgonpf07bbp4p FOREIGN KEY (student_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.shifts
    ADD CONSTRAINT fkb85voqs6elena0605m6uj3bbp FOREIGN KEY (cleaner_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkdn7tvyxt0pb47kudo6f97jauk FOREIGN KEY (student_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT fkm1lhvq5dln46j1vy4rrkx8rc0 FOREIGN KEY (occupant_id) REFERENCES public.users(id);
