CREATE TABLE public.organizations (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    slug character varying(60) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);

ALTER TABLE public.organizations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organizations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT uk_organization_slug UNIQUE (slug);
