-- Opake, database-backed sessietokens ter vervanging van zelf-ondertekende
-- JWT's. In tegenstelling tot een JWT is een rij hier server-side in te
-- trekken (logout, wachtwoordwijziging, een gebruiker verwijderen) zonder
-- op de expiry te hoeven wachten.

CREATE TABLE public.auth_sessions (
    id bigint NOT NULL,
    token character varying(64) NOT NULL,
    user_id bigint NOT NULL,
    organization_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    last_used_at timestamp(6) with time zone,
    expires_at timestamp(6) with time zone NOT NULL,
    revoked_at timestamp(6) with time zone
);

ALTER TABLE public.auth_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT uk_auth_session_token UNIQUE (token);

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT fk_auth_sessions_user FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT fk_auth_sessions_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id);

CREATE INDEX idx_auth_sessions_user ON public.auth_sessions USING btree (user_id);

CREATE INDEX idx_auth_sessions_expires_at ON public.auth_sessions USING btree (expires_at);
